"use client";

import { useState } from "react";
import { toast } from "sonner";
import { BookIcon, PlusIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { ColorBadge, type BadgeTone } from "@/components/color-badge";
import { EmptyState, ErrorState, TableSkeletonRows } from "@/components/data-states";
import { sanitizeInteger } from "@/lib/form-numeric";
import { BookletStatus, BookletType } from "@/generated/prisma/enums";
import { BOOKLET_PREFIX, BOOKLET_TYPE_LABEL } from "../schemas/booklet";
import {
  useBookletAction,
  useBookletSuggestion,
  useBooklets,
  useCreateBooklet,
  useDeleteBooklet,
} from "../hooks/use-sales-audit";

// Receipt booklets only — DR numbering is auto-generated by the DR module.
// The Sales Invoice labels are grouped BY NUMBER LINE, not by document: VAT and
// Charge Invoice share one continuous IN series, Non-VAT is printed as its own
// NV series. Which group a label sits in is the whole thing an admin needs to
// know here, since it decides what range gets suggested and what counts as an
// overlap. Each heading carries the "Sales Invoice" half of the name so the
// items stay short enough not to clip.
const TYPE_GROUPS: {
  heading: string;
  items: { type: BookletType; text: string }[];
}[] = [
  {
    heading: "Sales Invoice — one continuous IN series",
    items: [
      { type: BookletType.SI_VAT, text: "VAT" },
      { type: BookletType.SI_CHARGE, text: "Charge Invoice" },
    ],
  },
  {
    heading: "Sales Invoice — separate NV series",
    items: [{ type: BookletType.SI_NON_VAT, text: "Non-VAT" }],
  },
  {
    heading: "Other receipts",
    items: [
      { type: BookletType.JO_SLIP, text: "Job Order Receipt" },
      { type: BookletType.CR, text: "Collection Receipt" },
    ],
  },
];

const STATUS_TONE: Record<BookletStatus, BadgeTone> = {
  UNOPENED: "gray",
  PENDING_APPROVAL: "amber",
  ACTIVE: "green",
  REJECTED: "red",
  CONSUMED: "blue",
  CLOSED: "gray",
};

const STATUS_LABEL: Record<BookletStatus, string> = {
  UNOPENED: "Unopened",
  PENDING_APPROVAL: "For approval",
  ACTIVE: "Active",
  REJECTED: "Rejected",
  CONSUMED: "Fully consumed",
  CLOSED: "Closed",
};

const COLS = 7;

/**
 * The booklet register — the new home of the legacy Doc_Series sheet.
 * A cashier registers a booklet; an admin approves it into service. Only one
 * booklet per type can be active, so "the next number" is never ambiguous.
 */
export function BookletManager({ canApprove }: { canApprove: boolean }) {
  const query = useBooklets();
  const action = useBookletAction();
  const remove = useDeleteBooklet();
  const [adding, setAdding] = useState(false);

  const run = (
    id: string,
    verb: "approve" | "reject" | "re-request" | "close",
    done: string,
    note?: string
  ) =>
    action.mutate(
      { id, action: verb, note },
      {
        onSuccess: () => toast.success(done),
        onError: (e: Error) => toast.error(e.message),
      }
    );

  const booklets = query.data ?? [];

  return (
    <Card className="py-0">
      <CardHeader className="flex flex-row items-start justify-between gap-3 space-y-0 px-6 pt-6">
        <div className="grid gap-1">
          <CardTitle className="flex items-center gap-2">
            <BookIcon className="size-4" /> Receipt booklets
          </CardTitle>
          <p className="text-sm text-muted-foreground">
            The BIR booklets that Sales Invoices, Job Order Receipts and
            Collection Receipts draw their numbers from. A booklet must be
            approved before it can issue anything, and only one per type can be
            active at a time.
          </p>
        </div>
        <Button size="sm" onClick={() => setAdding(true)}>
          <PlusIcon /> Register booklet
        </Button>
      </CardHeader>

      <CardContent className="overflow-x-auto px-0 pb-0">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Type</TableHead>
              <TableHead>Range</TableHead>
              <TableHead>Next number</TableHead>
              <TableHead>Used</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Opened by</TableHead>
              <TableHead>Action</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {query.isPending ? (
              <TableSkeletonRows cols={COLS} />
            ) : query.isError ? (
              <TableRow>
                <TableCell colSpan={COLS}>
                  <ErrorState
                    message={query.error.message}
                    onRetry={() => query.refetch()}
                  />
                </TableCell>
              </TableRow>
            ) : booklets.length === 0 ? (
              <TableRow>
                <TableCell colSpan={COLS}>
                  <EmptyState
                    title="No booklets yet"
                    description="Register your first booklet — receipts can't be issued until one is approved and active."
                  />
                </TableCell>
              </TableRow>
            ) : (
              booklets.map((b) => (
                <TableRow key={b.id}>
                  <TableCell>
                    <div className="grid gap-0.5">
                      <span className="font-medium">{b.typeLabel}</span>
                      {b.label && (
                        <span className="text-xs text-muted-foreground">
                          {b.label}
                        </span>
                      )}
                      {b.gapExempt && <ColorBadge tone="gray" label="Gap-exempt" />}
                      {/* `prefix` is what was PRINTED on this pad, so it never
                          moves once the booklet exists — renumbering paper is
                          not a thing the software may do. When the TYPE has
                          since been re-pointed at another line (Non-VAT moved
                          from IN to NV), say so out loud: left silent, this
                          pad keeps issuing on the old line and nobody notices
                          until the BIR asks why a Non-VAT sale took an IN
                          serial. */}
                      {b.prefix !== BOOKLET_PREFIX[b.type] && (
                        <>
                          <ColorBadge
                            tone="amber"
                            label={`On the ${b.prefix} line, not ${BOOKLET_PREFIX[b.type]}`}
                          />
                          <span className="max-w-52 text-xs text-muted-foreground">
                            Pre-printed before {BOOKLET_TYPE_LABEL[b.type]} moved
                            to its own series. It will keep issuing{" "}
                            {b.prefix}-numbers
                            {b.used === 0
                              ? " — close and delete it to re-register on the " +
                                BOOKLET_PREFIX[b.type] +
                                " line."
                              : ", which is correct for leaves already printed."}
                          </span>
                        </>
                      )}
                    </div>
                  </TableCell>
                  <TableCell className="font-mono text-sm tabular-nums">
                    {b.prefix}-{String(b.seriesStart).padStart(4, "0")} →{" "}
                    {b.prefix}-{String(b.seriesEnd).padStart(4, "0")}
                  </TableCell>
                  <TableCell className="font-mono text-sm font-semibold tabular-nums">
                    {b.nextDocumentNo ?? (
                      <span className="font-sans font-normal text-muted-foreground">
                        —
                      </span>
                    )}
                  </TableCell>
                  <TableCell className="tabular-nums">
                    <span className="text-sm">
                      {b.used} / {b.capacity}
                    </span>
                    <div className="mt-1 h-1 w-20 overflow-hidden rounded-full bg-muted">
                      <div
                        className="h-full bg-primary"
                        style={{
                          width: `${Math.round((b.used / b.capacity) * 100)}%`,
                        }}
                      />
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="grid justify-items-start gap-1">
                      <ColorBadge
                        tone={STATUS_TONE[b.status]}
                        label={STATUS_LABEL[b.status]}
                      />
                      {b.rejectionNote && (
                        <span className="max-w-40 text-xs text-muted-foreground">
                          {b.rejectionNote}
                        </span>
                      )}
                    </div>
                  </TableCell>
                  <TableCell className="text-sm text-muted-foreground">
                    {b.openedByName}
                    {b.approvedByName && (
                      <div className="text-xs">
                        approved by {b.approvedByName}
                      </div>
                    )}
                  </TableCell>
                  <TableCell>
                    <div className="flex flex-wrap gap-1">
                      {canApprove && b.status === "PENDING_APPROVAL" && (
                        <>
                          <Button
                            size="sm"
                            onClick={() =>
                              run(b.id, "approve", `${b.typeLabel} booklet is now active.`)
                            }
                          >
                            Approve
                          </Button>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => {
                              const note = window.prompt("Reason for rejecting?") ?? "";
                              run(b.id, "reject", "Booklet request rejected.", note);
                            }}
                          >
                            Reject
                          </Button>
                        </>
                      )}
                      {canApprove && b.status === "UNOPENED" && (
                        <Button
                          size="sm"
                          onClick={() =>
                            run(b.id, "approve", `${b.typeLabel} booklet is now active.`)
                          }
                        >
                          Activate
                        </Button>
                      )}
                      {b.status === "REJECTED" && (
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() =>
                            run(b.id, "re-request", "Booklet re-submitted for approval.")
                          }
                        >
                          Re-submit
                        </Button>
                      )}
                      {canApprove && b.status === "ACTIVE" && (
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => {
                            if (
                              window.confirm(
                                `Close this booklet early? ${b.remaining} number(s) will go unused.`
                              )
                            ) {
                              run(b.id, "close", "Booklet closed.");
                            }
                          }}
                        >
                          Close
                        </Button>
                      )}
                      {canApprove && b.used === 0 && b.status !== "ACTIVE" && (
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => {
                            if (window.confirm("Delete this booklet?")) {
                              remove.mutate(b.id, {
                                onSuccess: () => toast.success("Booklet deleted."),
                                onError: (e: Error) => toast.error(e.message),
                              });
                            }
                          }}
                        >
                          Delete
                        </Button>
                      )}
                    </div>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </CardContent>

      <RegisterBookletDialog open={adding} onClose={() => setAdding(false)} />
    </Card>
  );
}

/** Register a booklet. The range is suggested from the last one, but the admin
 *  sizes it — a 25-, 50- or 100-leaf booklet all work. */
function RegisterBookletDialog({
  open,
  onClose,
}: {
  open: boolean;
  onClose: () => void;
}) {
  const [type, setType] = useState<BookletType>(BookletType.SI_VAT);
  // null → untouched, so the fields show the suggested next free block for the
  // chosen type. Derived from the query, not synced into state by an effect.
  const [startEdit, setStartEdit] = useState<string | null>(null);
  const [endEdit, setEndEdit] = useState<string | null>(null);
  const [label, setLabel] = useState("");
  const [gapExempt, setGapExempt] = useState(false);
  const create = useCreateBooklet();
  const suggestion = useBookletSuggestion(open ? type : null);

  const start = startEdit ?? suggestion.data?.suggestedStart.toString() ?? "";
  const end = endEdit ?? suggestion.data?.suggestedEnd.toString() ?? "";

  const pickType = (next: BookletType) => {
    setType(next);
    // Re-suggest from the new type's number line. Switching between VAT and
    // Charge Invoice keeps the range continuous — they share the IN line —
    // while switching to Non-VAT jumps to wherever the NV line has got to.
    setStartEdit(null);
    setEndEdit(null);
  };

  const reset = () => {
    setType(BookletType.SI_VAT);
    setStartEdit(null);
    setEndEdit(null);
    setLabel("");
    setGapExempt(false);
    onClose();
  };

  const startN = parseInt(start, 10);
  const endN = parseInt(end, 10);
  const valid = startN > 0 && endN >= startN;
  const count = valid ? endN - startN + 1 : 0;

  const submit = () =>
    create.mutate(
      {
        type,
        seriesStart: startN,
        seriesEnd: endN,
        label: label.trim() || undefined,
        gapExempt,
      },
      {
        onSuccess: () => {
          toast.success("Booklet registered — awaiting admin approval.");
          reset();
        },
        onError: (e: Error) => toast.error(e.message),
      }
    );

  return (
    <Dialog open={open} onOpenChange={(o) => !o && reset()}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>Register a booklet</DialogTitle>
          <DialogDescription>
            Enter the pre-printed number range from the physical booklet. It
            becomes usable once an admin approves it.
          </DialogDescription>
        </DialogHeader>

        <div className="grid gap-4">
          <div className="grid gap-1.5">
            <Label htmlFor="bk-type">Document type</Label>
            <Select
              value={type}
              onValueChange={(v) => pickType(v as BookletType)}
            >
              {/* Full width to line up with the number fields below, and the
                  items short enough that none of them clip. */}
              <SelectTrigger id="bk-type" className="w-full">
                <SelectValue>
                  {(v) => BOOKLET_TYPE_LABEL[v as BookletType]}
                </SelectValue>
              </SelectTrigger>
              {/* Drop below the field instead of overlaying it — with headings
                  in the list, sitting on top of the trigger reads as a mess. */}
              <SelectContent align="start" alignItemWithTrigger={false}>
                {TYPE_GROUPS.map((g) => (
                  <SelectGroup key={g.heading}>
                    <SelectLabel>{g.heading}</SelectLabel>
                    {g.items.map((i) => (
                      <SelectItem key={i.type} value={i.type}>
                        {i.text}
                      </SelectItem>
                    ))}
                  </SelectGroup>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="grid gap-1.5">
              <Label htmlFor="bk-start">First number</Label>
              <Input
                id="bk-start"
                inputMode="numeric"
                value={start}
                onChange={(e) => setStartEdit(sanitizeInteger(e.target.value))}
                className="font-mono tabular-nums"
              />
            </div>
            <div className="grid gap-1.5">
              <Label htmlFor="bk-end">Last number</Label>
              <Input
                id="bk-end"
                inputMode="numeric"
                value={end}
                onChange={(e) => setEndEdit(sanitizeInteger(e.target.value))}
                className="font-mono tabular-nums"
              />
            </div>
          </div>

          <p className="text-sm text-muted-foreground">
            {valid ? (
              <>
                <strong className="text-foreground">{count}</strong> leaves,{" "}
                <span className="font-mono">
                  {suggestion.data?.prefix}-{String(startN).padStart(4, "0")}
                </span>{" "}
                through{" "}
                <span className="font-mono">
                  {suggestion.data?.prefix}-{String(endN).padStart(4, "0")}
                </span>
                .
              </>
            ) : (
              "Enter a valid range — the last number can't be lower than the first."
            )}
          </p>

          <div className="grid gap-1.5">
            <Label htmlFor="bk-label">Label (optional)</Label>
            <Input
              id="bk-label"
              value={label}
              onChange={(e) => setLabel(e.target.value)}
              placeholder="e.g. 2026 batch 1"
            />
          </div>

          <label className="flex items-start gap-2 text-sm">
            <input
              type="checkbox"
              checked={gapExempt}
              onChange={(e) => setGapExempt(e.target.checked)}
              className="mt-1"
            />
            <span>
              Gap-exempt
              <span className="block text-xs text-muted-foreground">
                Don&apos;t flag missing numbers in this booklet — for leaves
                voided before they were recorded here.
              </span>
            </span>
          </label>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={reset}>
            Cancel
          </Button>
          <Button onClick={submit} disabled={!valid || create.isPending}>
            {create.isPending ? "Registering…" : "Register"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
